---
version: "3.1"
services:
  transmission:
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - "node.role!=manager"
    image: lscr.io/linuxserver/transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - SMB_USERNAME=/run/secrets/viktorUserName
      - SMB_PASSWORD=/run/secrets/viktorPassword
      - SMB_IPADDRESS=10.0.1.10
      - CIF_VERSION=2.0
    volumes:
      - config:/config
      - download:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    secrets:
      - viktorUserName
      - viktorPassword
    restart: unless-stopped
    labels:
      - traefik.http.routers.transmission.rule=Host(`host.docker.internal`)
      - traefik.http.services.transmission-service.loadbalancer.server.port=9091
volumes:
  download:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=${CIF_VERSION}"
      device: "//${SMB_IPADDRESS}/download"
  config:
    driver: local
secrets:
  viktorUserName:
    external: true
  viktorPassword:
    external: true
