---
version: "3.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Melbourne
      - TRANSMISSION_WEB_HOME=/combustion-release/ 
      - SMB_USERNAME: /run/secrets/viktorUserName
      - SMB_PASSWORD: /run/secrets/viktorPassword
    volumes:
      - config:/config
      - download:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    secrets:
	  - viktorUserName
	  - viktorPassword
    restart: unless-stopped	
volumes:
  download:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=2.0"
      device: "//10.0.1.10/download"
  config:
    driver: local
secrets:
  viktorUserName:
    external: true
  viktorPassword:
    external: true
